### ISSUE TITLE
Render area selection color according to the task assigned

### ISSUE THREAD

**Issue by Naman-sopho** [Terasology/MasterOfOreon#16]
The color rendered for the area selection currently is chosen randomly, this should be changed to a particular color for each task for a better gameplay experience.
Colors can be:
- Green -> Plant task
- Brown -> Build task
- Blue/Red -> Guard task etc.

**Comment by mkienenb** [comment]
Pretty sure this is trivial to do -- there's a block selection component field you can set.   See the original Miniion code.
