### ISSUE TITLE
New blocks added after building upgrade not included in building regions

### ISSUE THREAD

**Issue by Naman-sopho** [Terasology/MasterOfOreon#38]
When "activating" a block with the Building Upgrade Tool the `BuildingUpgradeSystem` triggers the upgrade screen only if the block is part of a building.
New blocks that are added in the world after a building upgrade are not included in this list of block regions thus, activating these with the Upgrade Tool do not trigger the required screen.
The `HoldingComponent` attached to the player has a list of constructed buildings which also consists of details about the bounding regions of these buildings. This list must be updated after each upgrade.

**Comment by shaunakdixit** [comment]
hy @Naman-sopho I tried to reproduce the issue but I was not able to do it.
I build a diner then upgraded it but still each and every block of building is able to trigger upgrade screen.
Please tell me if I'm doing anything wrong :-)

**Comment by namtiw** [comment]
Hey @shaunakdixit the issue arises when _new_ blocks are added to the building after upgrade. To reproduce you can try the building in the PR #36. This PR also has an initial implementation for this feature but it is buggy. Refer to the comment on the PR for details.
