### ISSUE TITLE
Debug Oreon spawn, and add resource based spawn from Portals

### ISSUE THREAD

**Issue by Naman-sopho** [Terasology/MasterOfOreon#4]
The Oreons are currently spawned, provided rather inconsistently, using the summon menu. This should be changed to a resource based spawn, wherein the player would have to give up certain resources to spawn Oreons from the [Portal](https://github.com/Terasology/Portals). Main issue [here](https://github.com/MovingBlocks/Terasology/issues/2078).
Code related to the following has been deleted as part of the issue #3 resolution, in the corresponding PR, so listing them here for future reference :
* Currently for spawning MOO uses the `SummonMinionMenuSystem` from the Miniion module using the `createMinion` method from the class.
* The menu system also lists out all the Oreons that can be spawned by filtering entities with `MinionComponent`.

**Comment by Cervator** [comment]
Completed by #6
