### ISSUE TITLE
Parsing of text rendering on the Getting Started Manual

### ISSUE THREAD

**Issue by agent-q1** [Terasology/MasterOfOreon#66]
## Text rendered as \n instead of newline

![Screenshot from 2020-04-25 20-53-09](https://user-images.githubusercontent.com/35196657/80283674-17c5a000-8737-11ea-9a05-9fc82195054e.png)

**Comment by jdrueckert** [comment]
Should be the same issue and thus should be fixable the same way as in https://github.com/Terasology/MasterOfOreon/pull/70

**Comment by jdrueckert** [comment]
Fixed in https://github.com/Terasology/MasterOfOreon/pull/70
